### ISSUE TITLE
Poppler subprocess doesn't work on Windows

### ISSUE THREAD

**Issue by LucieTomiskova** [KENDAXA-Development/pdf-utils#11]
Poppler subprocess doesn't work on Windows.

Poppler subprocess should work for all the following platforms: Linux, OSX and Windows.

Error:
Can not reproduce the issue. Before there was an issue running the subprocess on Windows platform, but apparently it might work even without this implementation.

**Comment by franp9am** [comment]
This error doesn't seem to be related to Poppler. Seems more like you have no `Tesseract` installed.

**Comment by franp9am** [comment]
Possible problem has been possibly fixed by this commit https://github.com/KENDAXA-Development/pdf-utils/commit/17aade96715d160a92516412ba95d37b3eabaa89
